using ImageMagick;
using ImageMagick.Drawing;
using static QRCoder.ArtQRCode;
using static QRCoder.QRCodeGenerator;

namespace QRCoder;

/// <summary>
/// Represents an art-style QR code generator that provides functionality to render QR codes with dots as modules.
/// </summary>
public class ArtQRCode : AbstractQRCode, IDisposable
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ArtQRCode"/> class.
    /// Constructor without params to be used in COM Objects connections
    /// </summary>
    public ArtQRCode() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="ArtQRCode"/> class with the specified <see cref="QRCodeData"/>.
    /// </summary>
    /// <param name="data"><see cref="QRCodeData"/> generated by the <see cref="QRCodeGenerator"/>.</param>
    public ArtQRCode(QRCodeData data) : base(data) { }

    /// <summary>
    /// Renders an art-style QR code with dots as modules. (With default settings: DarkColor=Black, LightColor=White, Background=Transparent, QuietZone=true)
    /// </summary>
    /// <param name="pixelsPerModule">Amount of px each dark/light module of the QR code shall take place in the final QR code image</param>
    /// <returns>QRCode graphic as <see cref="MagickImage"/></returns>
    public MagickImage GetGraphic(int pixelsPerModule)
        => GetGraphic(pixelsPerModule, MagickColors.Black, MagickColors.White, MagickColors.Transparent);

    /// <summary>
    /// Renders an art-style QR code with dots as modules and a background image (With default settings: DarkColor=Black, LightColor=White, Background=Transparent, QuietZone=true)
    /// </summary>
    /// <param name="backgroundImage">An image that will be used as background picture</param>
    /// <returns>QRCode graphic as <see cref="MagickImage"/></returns>
    public MagickImage GetGraphic(IMagickImage<byte>? backgroundImage = null)
        => GetGraphic(10, MagickColors.Black, MagickColors.White, MagickColors.Transparent, backgroundImage: backgroundImage);

    /// <summary>
    /// Renders an art-style QR code with dots as modules and various user settings
    /// </summary>
    /// <param name="pixelsPerModule">Amount of px each dark/light module of the QR code shall take place in the final QR code image</param>
    /// <param name="darkColor">Color of the dark modules</param>
    /// <param name="lightColor">Color of the light modules</param>
    /// <param name="backgroundColor">Color of the background</param>
    /// <param name="backgroundImage">An image that will be used as background picture</param>
    /// <param name="pixelSizeFactor">Value between 0.0 to 1.0 that defines how big the module dots are. The bigger the value, the less round the dots will be.</param>
    /// <param name="drawQuietZones">If true a white border is drawn around the whole QR Code</param>
    /// <param name="quietZoneRenderingStyle">Style of the quiet zones</param>
    /// <param name="backgroundImageStyle">Style of the background image (if set). Fill=spanning complete graphic; DataAreaOnly=Don't paint background into quietzone</param>
    /// <param name="finderPatternImage">Optional image that should be used instead of the default finder patterns</param>
    /// <returns>QRCode graphic as <see cref="MagickImage"/></returns>
    public MagickImage GetGraphic(int pixelsPerModule, MagickColor darkColor, MagickColor lightColor, MagickColor backgroundColor, IMagickImage<byte>? backgroundImage = null, double pixelSizeFactor = 1,
                                  bool drawQuietZones = true, QuietZoneStyle quietZoneRenderingStyle = QuietZoneStyle.Dotted,
                                  BackgroundImageStyle backgroundImageStyle = BackgroundImageStyle.DataAreaOnly, IMagickImage<byte>? finderPatternImage = null)
    {
        if (pixelSizeFactor > 1)
            throw new ArgumentOutOfRangeException(nameof(pixelSizeFactor), "The parameter pixelSizeFactor must be between 0 and 1. (0-100%)");
        int pixelSize = (int)Math.Min(pixelsPerModule, Math.Floor(pixelsPerModule * pixelSizeFactor));

        var numModules = QrCodeData.ModuleMatrix.Count - (drawQuietZones ? 0 : 8);
        var offset = (drawQuietZones ? 0 : 4);
        var size = numModules * pixelsPerModule;

        // Start with the background color
        var image = new MagickImage(backgroundColor, (uint)size, (uint)size)
        {
            Format = MagickFormat.Png32
        };

        //Render background if set
        if (backgroundImage != null)
        {
            if (backgroundImageStyle == BackgroundImageStyle.Fill)
            {
                using var resizedBg = Resize(backgroundImage, size);
                image.Composite(resizedBg, 0, 0, CompositeOperator.Over);
            }
            else if (backgroundImageStyle == BackgroundImageStyle.DataAreaOnly)
            {
                var bgOffset = 4 - offset;
                using var resizedBg = Resize(backgroundImage, size - (2 * bgOffset * pixelsPerModule));
                image.Composite(resizedBg, bgOffset * pixelsPerModule, bgOffset * pixelsPerModule, CompositeOperator.Over);
            }
        }

        using var darkModulePixel = MakeDotPixel(pixelsPerModule, pixelSize, darkColor);
        using var lightModulePixel = MakeDotPixel(pixelsPerModule, pixelSize, lightColor);

        IDrawables<byte> flatDrawables = new Drawables().StrokeWidth(0).StrokeColor(MagickColors.Transparent);
        var hasFlatDrawables = false;

        for (var x = 0; x < numModules; x += 1)
        {
            for (var y = 0; y < numModules; y += 1)
            {
                var moduleX = x * pixelsPerModule;
                var moduleY = y * pixelsPerModule;

                var pixelIsDark = QrCodeData.ModuleMatrix[offset + y][offset + x];
                var moduleColor = pixelIsDark ? darkColor : lightColor;
                var pixelImage = pixelIsDark ? darkModulePixel : lightModulePixel;

                if (!IsPartOfFinderPattern(x, y, numModules, offset))
                {
                    if (drawQuietZones && quietZoneRenderingStyle == QuietZoneStyle.Flat && IsPartOfQuietZone(x, y, numModules))
                    {
                        flatDrawables.FillColor(moduleColor).Rectangle(moduleX, moduleY, moduleX + pixelsPerModule - 1, moduleY + pixelsPerModule - 1);
                        hasFlatDrawables = true;
                    }
                    else
                    {
                        image.Composite(pixelImage, moduleX, moduleY, CompositeOperator.Over);
                    }
                }
                else if (finderPatternImage == null)
                {
                    flatDrawables.FillColor(moduleColor).Rectangle(moduleX, moduleY, moduleX + pixelsPerModule - 1, moduleY + pixelsPerModule - 1);
                    hasFlatDrawables = true;
                }
            }
        }

        if (hasFlatDrawables)
            flatDrawables.Draw(image);

        if (finderPatternImage != null)
        {
            var finderPatternSize = 7 * pixelsPerModule;
            var finderPatternOffset = drawQuietZones ? 4 * pixelsPerModule : 0;
            using var resizedFinderPattern = finderPatternImage.Clone();
            resizedFinderPattern.Resize(new MagickGeometry((uint)finderPatternSize, (uint)finderPatternSize) { IgnoreAspectRatio = true });
            image.Composite(resizedFinderPattern, finderPatternOffset, finderPatternOffset, CompositeOperator.Over);
            image.Composite(resizedFinderPattern, size - finderPatternOffset - finderPatternSize, finderPatternOffset, CompositeOperator.Over);
            image.Composite(resizedFinderPattern, finderPatternOffset, size - finderPatternOffset - finderPatternSize, CompositeOperator.Over);
        }

        return image;
    }

    /// <summary>
    /// If the pixelSize is bigger than the pixelsPerModule or may end up filling the Module making a traditional QR code.
    /// </summary>
    /// <param name="pixelsPerModule">Pixels used per module rendered</param>
    /// <param name="pixelSize">Size of the dots</param>
    /// <param name="color">Color of the pixels</param>
    /// <returns>A single module tile containing a centered dot</returns>
    private static MagickImage MakeDotPixel(int pixelsPerModule, int pixelSize, MagickColor color)
    {
        var pixelWidth = Math.Min(pixelsPerModule, pixelSize);
        var margin = Math.Max((pixelsPerModule - pixelWidth) / 2, 0);

        // Center the dot within a transparent module-sized tile.
        var tile = new MagickImage(MagickColors.Transparent, (uint)pixelsPerModule, (uint)pixelsPerModule)
        {
            Format = MagickFormat.Png32
        };

        var radius = pixelWidth / 2d;
        var centerX = margin + radius;
        var centerY = margin + radius;

        new Drawables()
            .StrokeWidth(0)
            .StrokeColor(MagickColors.Transparent)
            .FillColor(color)
            .Ellipse(centerX, centerY, radius, radius, 0, 360)
            .Draw(tile);

        return tile;
    }

    /// <summary>
    /// Checks if a given module(-position) is part of the quietzone of a QR code
    /// </summary>
    /// <param name="x">X position</param>
    /// <param name="y">Y position</param>
    /// <param name="numModules">Total number of modules per row</param>
    /// <returns>true, if position is part of quiet zone</returns>
    private static bool IsPartOfQuietZone(int x, int y, int numModules)
    {
        return
            x < 4 || //left 
            y < 4 || //top
            x > numModules - 5 || //right
            y > numModules - 5; //bottom                
    }

    /// <summary>
    /// Checks if a given module(-position) is part of one of the three finder patterns of a QR code
    /// </summary>
    /// <param name="x">X position</param>
    /// <param name="y">Y position</param>
    /// <param name="numModules">Total number of modules per row</param>
    /// <param name="offset">Offset in modules (usually depending on drawQuietZones parameter)</param>
    /// <returns>true, if position is part of any finder pattern</returns>
    private static bool IsPartOfFinderPattern(int x, int y, int numModules, int offset)
    {
        var cornerSize = 11 - offset;
        var outerLimitLow = (numModules - cornerSize - 1);
        var outerLimitHigh = outerLimitLow + 8;
        var invertedOffset = 4 - offset;
        return
            (x >= invertedOffset && x < cornerSize && y >= invertedOffset && y < cornerSize) || //Top-left finder pattern
            (x > outerLimitLow && x < outerLimitHigh && y >= invertedOffset && y < cornerSize) || //Top-right finder pattern
            (x >= invertedOffset && x < cornerSize && y > outerLimitLow && y < outerLimitHigh); //Bottom-left finder pattern
    }

    /// <summary>
    /// Resize to a square image, but maintain the aspect ratio by padding transparently.
    /// </summary>
    /// <param name="image">The image to resize</param>
    /// <param name="newSize">The edge length of the resulting square image</param>
    /// <returns>Resized image</returns>
    private static MagickImage Resize(IMagickImage<byte> image, int newSize)
    {
        var resized = (MagickImage)image.Clone();
        resized.Format = MagickFormat.Png32;
        resized.BackgroundColor = MagickColors.Transparent;

        // Resize preserving aspect ratio, then pad transparently to a square.
        resized.Resize(new MagickGeometry((uint)newSize, (uint)newSize));
        resized.Extent(new MagickGeometry((uint)newSize, (uint)newSize), Gravity.Center, MagickColors.Transparent);

        return resized;
    }

    /// <summary>
    /// Defines how the quiet zones shall be rendered.
    /// </summary>
    public enum QuietZoneStyle
    {
        /// <summary>
        /// Quiet zones are rendered with dotted modules.
        /// </summary>
        Dotted,

        /// <summary>
        /// Quiet zones are rendered with flat, solid modules.
        /// </summary>
        Flat
    }

    /// <summary>
    /// Defines how the background image (if set) shall be rendered.
    /// </summary>
    public enum BackgroundImageStyle
    {
        /// <summary>
        /// Background image spans the complete graphic.
        /// </summary>
        Fill,

        /// <summary>
        /// Background image is only painted in the data area, excluding the quiet zone.
        /// </summary>
        DataAreaOnly
    }
}

/// <summary>
/// Provides static methods for creating art-style QR codes.
/// </summary>
public static class ArtQRCodeHelper
{
    /// <summary>
    /// Helper function to create an ArtQRCode graphic with a single function call
    /// </summary>
    /// <param name="plainText">Text/payload to be encoded inside the QR code</param>
    /// <param name="pixelsPerModule">Amount of px each dark/light module of the QR code shall take place in the final QR code image</param>
    /// <param name="darkColor">Color of the dark modules</param>
    /// <param name="lightColor">Color of the light modules</param>
    /// <param name="backgroundColor">Color of the background</param>
    /// <param name="eccLevel">The level of error correction data</param>
    /// <param name="forceUtf8">Shall the generator be forced to work in UTF-8 mode?</param>
    /// <param name="utf8BOM">Should the byte-order-mark be used?</param>
    /// <param name="eciMode">Which ECI mode shall be used?</param>
    /// <param name="requestedVersion">Set fixed QR code target version.</param>
    /// <param name="backgroundImage">An image that will be used as background picture</param>
    /// <param name="pixelSizeFactor">Value between 0.0 to 1.0 that defines how big the module dots are. The bigger the value, the less round the dots will be.</param>
    /// <param name="drawQuietZones">If true a white border is drawn around the whole QR Code</param>
    /// <param name="quietZoneRenderingStyle">Style of the quiet zones</param>
    /// <param name="backgroundImageStyle">Style of the background image (if set). Fill=spanning complete graphic; DataAreaOnly=Don't paint background into quietzone</param>
    /// <param name="finderPatternImage">Optional image that should be used instead of the default finder patterns</param>
    /// <returns>QRCode graphic as <see cref="MagickImage"/></returns>
    public static MagickImage GetQRCode(string plainText, int pixelsPerModule, MagickColor darkColor, MagickColor lightColor, MagickColor backgroundColor, ECCLevel eccLevel, bool forceUtf8 = false,
                                        bool utf8BOM = false, EciMode eciMode = EciMode.Default, int requestedVersion = -1, IMagickImage<byte>? backgroundImage = null, double pixelSizeFactor = 1.0,
                                        bool drawQuietZones = true, QuietZoneStyle quietZoneRenderingStyle = QuietZoneStyle.Flat,
                                        BackgroundImageStyle backgroundImageStyle = BackgroundImageStyle.DataAreaOnly, IMagickImage<byte>? finderPatternImage = null)
    {
        using var qrGenerator = new QRCodeGenerator();
        using var qrCodeData = qrGenerator.CreateQrCode(plainText, eccLevel, forceUtf8, utf8BOM, eciMode, requestedVersion);
        using var qrCode = new ArtQRCode(qrCodeData);
        return qrCode.GetGraphic(pixelsPerModule, darkColor, lightColor, backgroundColor, backgroundImage, pixelSizeFactor, drawQuietZones, quietZoneRenderingStyle, backgroundImageStyle, finderPatternImage);
    }
}
