using ImageMagick;
using static QRCoder.Base64QRCode;
using static QRCoder.QRCodeGenerator;

namespace QRCoder;

/// <summary>
/// Represents a QR code generator that outputs base64-encoded images.
/// </summary>
public class Base64QRCode : AbstractQRCode, IDisposable
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Base64QRCode"/> class.
    /// Constructor without parameters to be used in COM objects connections.
    /// </summary>
    public Base64QRCode()
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="Base64QRCode"/> class with the specified <see cref="QRCodeData"/>.
    /// </summary>
    /// <param name="data"><see cref="QRCodeData"/> generated by the QRCodeGenerator.</param>
    public Base64QRCode(QRCodeData data) : base(data)
    {
    }

    /// <summary>
    /// Returns a base64-encoded string that contains the resulting QR code as a PNG image.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <returns>Returns the QR code graphic as a base64-encoded string.</returns>
    public string GetGraphic(int pixelsPerModule)
        => GetGraphic(pixelsPerModule, MagickColors.Black, MagickColors.White, true);

    /// <summary>
    /// Returns a base64-encoded string that contains the resulting QR code as an image.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColorHtmlHex">The color of the dark modules in HTML hex format.</param>
    /// <param name="lightColorHtmlHex">The color of the light modules in HTML hex format.</param>
    /// <param name="drawQuietZones">Indicates if quiet zones around the QR code should be drawn.</param>
    /// <param name="imgType">The type of image to generate (PNG, JPEG, GIF).</param>
    /// <returns>Returns the QR code graphic as a base64-encoded string.</returns>
    public string GetGraphic(int pixelsPerModule, string darkColorHtmlHex, string lightColorHtmlHex, bool drawQuietZones = true, ImageType imgType = ImageType.Png)
        => GetGraphic(pixelsPerModule, new MagickColor(darkColorHtmlHex), new MagickColor(lightColorHtmlHex), drawQuietZones, imgType);

    /// <summary>
    /// Returns a base64-encoded string that contains the resulting QR code as an image.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColor">The color of the dark modules.</param>
    /// <param name="lightColor">The color of the light modules.</param>
    /// <param name="drawQuietZones">Indicates if quiet zones around the QR code should be drawn.</param>
    /// <param name="imgType">The type of image to generate (PNG, JPEG, GIF).</param>
    /// <returns>Returns the QR code graphic as a base64-encoded string.</returns>
    public string GetGraphic(int pixelsPerModule, MagickColor darkColor, MagickColor lightColor, bool drawQuietZones = true, ImageType imgType = ImageType.Png)
    {
        if (imgType == ImageType.Png)
        {
            var pngCoder = new PngByteQRCode(QrCodeData);

            byte[] pngData;
            if (darkColor == MagickColors.Black && lightColor == MagickColors.White)
            {
                pngData = pngCoder.GetGraphic(pixelsPerModule, drawQuietZones);
            }
            else
            {
                byte[] darkColorBytes;
                byte[] lightColorBytes;
                if (darkColor.A != 255 || lightColor.A != 255)
                {
                    darkColorBytes = new byte[] { darkColor.R, darkColor.G, darkColor.B, darkColor.A };
                    lightColorBytes = new byte[] { lightColor.R, lightColor.G, lightColor.B, lightColor.A };
                }
                else
                {
                    darkColorBytes = new byte[] { darkColor.R, darkColor.G, darkColor.B };
                    lightColorBytes = new byte[] { lightColor.R, lightColor.G, lightColor.B };
                }
                pngData = pngCoder.GetGraphic(pixelsPerModule, darkColorBytes, lightColorBytes, drawQuietZones);
            }

            return Convert.ToBase64String(pngData, Base64FormattingOptions.None);
        }

        var qr = new QRCode(QrCodeData);
        using var image = qr.GetGraphic(pixelsPerModule, darkColor, lightColor, drawQuietZones);
        return ImageToBase64(image, imgType);
    }

    /// <summary>
    /// Returns a base64-encoded string that contains the resulting QR code as an image with an embedded icon.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColor">The color of the dark modules.</param>
    /// <param name="lightColor">The color of the light modules.</param>
    /// <param name="icon">The icon to embed in the center of the QR code.</param>
    /// <param name="iconSizePercent">The size of the icon as a percentage of the QR code.</param>
    /// <param name="iconBorderWidth">The width of the border around the icon.</param>
    /// <param name="drawQuietZones">Indicates if quiet zones around the QR code should be drawn.</param>
    /// <param name="imgType">The type of image to generate (PNG, JPEG, GIF).</param>
    /// <returns>Returns the QR code graphic as a base64-encoded string.</returns>
    public string GetGraphic(int pixelsPerModule, MagickColor darkColor, MagickColor lightColor, IMagickImage<byte> icon, int iconSizePercent = 15, int iconBorderWidth = 6, bool drawQuietZones = true, ImageType imgType = ImageType.Png)
    {
        var qr = new QRCode(QrCodeData);
        using var image = qr.GetGraphic(pixelsPerModule, darkColor, lightColor, icon, iconSizePercent, iconBorderWidth, drawQuietZones);
        return ImageToBase64(image, imgType);
    }

    /// <summary>
    /// Converts an image to a base64-encoded string.
    /// </summary>
    /// <param name="image">The image to convert.</param>
    /// <param name="imgType">The type of image (PNG, JPEG, GIF).</param>
    /// <returns>Returns the base64-encoded string representation of the image.</returns>
    private static string ImageToBase64(MagickImage image, ImageType imgType)
    {
        var format = imgType switch
        {
            ImageType.Png => MagickFormat.Png32,
            ImageType.Jpeg => MagickFormat.Jpeg,
            ImageType.Gif => MagickFormat.Gif,
            _ => MagickFormat.Png32,
        };
        return Convert.ToBase64String(image.ToByteArray(format), Base64FormattingOptions.None);
    }

    /// <summary>
    /// Specifies the type of image to generate.
    /// </summary>
    public enum ImageType
    {
        /// <summary>
        /// Graphics Interchange Format (GIF) image format, a bitmap image format with limited color support
        /// </summary>
        Gif,
        /// <summary>
        /// Joint Photographic Experts Group (JPEG) image format, a lossy compressed image format
        /// </summary>
        Jpeg,
        /// <summary>
        /// Portable Network Graphics (PNG) image format, a lossless raster graphics format
        /// </summary>
        Png
    }

}

/// <summary>
/// Provides static methods for creating base64-encoded QR codes.
/// </summary>
public static class Base64QRCodeHelper
{
    /// <summary>
    /// Creates a base64-encoded QR code with a single function call.
    /// </summary>
    /// <param name="plainText">The text or payload to be encoded inside the QR code.</param>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColorHtmlHex">The color of the dark modules in HTML hex format.</param>
    /// <param name="lightColorHtmlHex">The color of the light modules in HTML hex format.</param>
    /// <param name="eccLevel">The level of error correction data.</param>
    /// <param name="forceUtf8">Specifies whether the generator should be forced to work in UTF-8 mode.</param>
    /// <param name="utf8BOM">Specifies whether the byte-order-mark should be used.</param>
    /// <param name="eciMode">Specifies which ECI mode should be used.</param>
    /// <param name="requestedVersion">Sets the fixed QR code target version.</param>
    /// <param name="drawQuietZones">Indicates if quiet zones around the QR code should be drawn.</param>
    /// <param name="imgType">The type of image to generate (PNG, JPEG, GIF).</param>
    /// <returns>Returns the QR code graphic as a base64-encoded string.</returns>
    public static string GetQRCode(string plainText, int pixelsPerModule, string darkColorHtmlHex, string lightColorHtmlHex, ECCLevel eccLevel, bool forceUtf8 = false, bool utf8BOM = false, EciMode eciMode = EciMode.Default, int requestedVersion = -1, bool drawQuietZones = true, ImageType imgType = ImageType.Png)
    {
        using var qrGenerator = new QRCodeGenerator();
        using var qrCodeData = qrGenerator.CreateQrCode(plainText, eccLevel, forceUtf8, utf8BOM, eciMode, requestedVersion);
        using var qrCode = new Base64QRCode(qrCodeData);
        return qrCode.GetGraphic(pixelsPerModule, darkColorHtmlHex, lightColorHtmlHex, drawQuietZones, imgType);
    }
}
