using ImageMagick;
using ImageMagick.Drawing;
using static QRCoder.QRCodeGenerator;

namespace QRCoder;

/// <summary>
/// Represents a QR code generator that outputs QR codes as raster images.
/// </summary>
public class QRCode : AbstractQRCode, IDisposable
{
    /// <summary>
    /// Initializes a new instance of the <see cref="QRCode"/> class.
    /// Constructor without parameters to be used in COM objects connections.
    /// </summary>
    public QRCode() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="QRCode"/> class with the specified <see cref="QRCodeData"/>.
    /// </summary>
    /// <param name="data"><see cref="QRCodeData"/> generated by the QRCodeGenerator.</param>
    public QRCode(QRCodeData data) : base(data) { }

    /// <summary>
    /// Creates a black and white image of the QR code.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <returns>Returns the QR code graphic as a <see cref="MagickImage"/>.</returns>
    public MagickImage GetGraphic(int pixelsPerModule)
        => GetGraphic(pixelsPerModule, MagickColors.Black, MagickColors.White, true);

    /// <summary>
    /// Creates a colored image of the QR code.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColorHtmlHex">The color of the dark modules in HTML hex format.</param>
    /// <param name="lightColorHtmlHex">The color of the light modules in HTML hex format.</param>
    /// <param name="drawQuietZones">Indicates if quiet zones around the QR code should be drawn.</param>
    /// <returns>Returns the QR code graphic as a <see cref="MagickImage"/>.</returns>
    public MagickImage GetGraphic(int pixelsPerModule, string darkColorHtmlHex, string lightColorHtmlHex, bool drawQuietZones = true)
        => GetGraphic(pixelsPerModule, new MagickColor(darkColorHtmlHex), new MagickColor(lightColorHtmlHex), drawQuietZones);

    /// <summary>
    /// Creates a colored image of the QR code.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColor">The color of the dark modules.</param>
    /// <param name="lightColor">The color of the light modules.</param>
    /// <param name="drawQuietZones">Indicates if quiet zones around the QR code should be drawn.</param>
    /// <returns>Returns the QR code graphic as a <see cref="MagickImage"/>.</returns>
    public MagickImage GetGraphic(int pixelsPerModule, MagickColor darkColor, MagickColor lightColor, bool drawQuietZones = true)
        => GetGraphic(pixelsPerModule, darkColor, lightColor, null, 0, 0, drawQuietZones, null);

    /// <summary>
    /// Creates a colored image of the QR code with an optional icon in the center.
    /// </summary>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColor">The color of the dark modules.</param>
    /// <param name="lightColor">The color of the light modules.</param>
    /// <param name="icon">An optional icon to be placed in the center of the QR code.</param>
    /// <param name="iconSizePercent">The size of the icon as a percentage of the QR code size.</param>
    /// <param name="iconBorderWidth">The width of the border around the icon.</param>
    /// <param name="drawQuietZones">Indicates if quiet zones around the QR code should be drawn.</param>
    /// <param name="iconBackgroundColor">The background color of the icon.</param>
    /// <returns>Returns the QR code graphic as a <see cref="MagickImage"/>.</returns>
    public MagickImage GetGraphic(int pixelsPerModule, MagickColor darkColor, MagickColor lightColor, IMagickImage<byte>? icon = null, int iconSizePercent = 15, int iconBorderWidth = 0, bool drawQuietZones = true, MagickColor? iconBackgroundColor = null)
    {
        var size = (QrCodeData.ModuleMatrix.Count - (drawQuietZones ? 0 : 8)) * pixelsPerModule;
        var offset = drawQuietZones ? 0 : 4 * pixelsPerModule;

        // Fill background with light color
        var image = new MagickImage(lightColor, (uint)size, (uint)size)
        {
            Format = MagickFormat.Png32
        };

        // Draw all dark modules using RLE-combined rectangles
        var drawables = new Drawables().StrokeWidth(0).StrokeColor(MagickColors.Transparent).FillColor(darkColor);
        AddModuleRectangles(drawables, pixelsPerModule, offset, drawQuietZones);
        drawables.Draw(image);

        var drawIconFlag = icon != null && iconSizePercent > 0 && iconSizePercent <= 100;
        if (drawIconFlag)
        {
            double iconDestWidth = iconSizePercent * image.Width / 100d;
            double iconDestHeight = iconDestWidth * icon!.Height / icon.Width;
            double iconX = (image.Width - iconDestWidth) / 2;
            double iconY = (image.Height - iconDestHeight) / 2;

            // Only render icon/logo background, if iconBorderWidth is set > 0
            if (iconBorderWidth > 0)
            {
                var backgroundColor = iconBackgroundColor ?? lightColor;
                new Drawables()
                    .StrokeWidth(0)
                    .StrokeColor(MagickColors.Transparent)
                    .FillColor(backgroundColor)
                    .RoundRectangle(
                        iconX - iconBorderWidth,
                        iconY - iconBorderWidth,
                        iconX + iconDestWidth + iconBorderWidth,
                        iconY + iconDestHeight + iconBorderWidth,
                        iconBorderWidth * 2,
                        iconBorderWidth * 2)
                    .Draw(image);
            }

            using var resizedIcon = icon!.Clone();
            resizedIcon.Resize(new MagickGeometry((uint)Math.Round(iconDestWidth), (uint)Math.Round(iconDestHeight)) { IgnoreAspectRatio = true });
            image.Composite(resizedIcon, (int)Math.Round(iconX), (int)Math.Round(iconY), CompositeOperator.Over);
        }

        return image;
    }

    /// <summary>
    /// Adds rectangles for all dark modules in the QR code to the specified drawables.
    /// Uses Run-Length Encoding (RLE) to combine adjoining dark modules in each row into single rectangles.
    /// </summary>
    /// <param name="drawables">The drawables to add the rectangles to.</param>
    /// <param name="pixelsPerModule">The number of pixels per module.</param>
    /// <param name="offset">The offset to apply for quiet zones.</param>
    /// <param name="drawQuietZones">Whether quiet zones are being drawn.</param>
    private void AddModuleRectangles(IDrawables<byte> drawables, int pixelsPerModule, int offset, bool drawQuietZones)
    {
        var matrix = QrCodeData.ModuleMatrix;
        var size = matrix.Count;
        var startIdx = drawQuietZones ? 0 : 4;
        var endIdx = drawQuietZones ? size : size - 4;

        for (int y = startIdx; y < endIdx; y++)
        {
            int x = startIdx;
            while (x < endIdx)
            {
                // Skip light modules
                if (!matrix[y][x])
                {
                    x++;
                    continue;
                }

                // Found a dark module - find the run length
                int startX = x;
                while (x < endIdx && matrix[y][x])
                {
                    x++;
                }

                // Create a single rectangle for the entire run of dark modules
                var rectX = startX * pixelsPerModule - offset;
                var rectY = y * pixelsPerModule - offset;
                var rectWidth = (x - startX) * pixelsPerModule;

                // Magick rectangle coordinates are inclusive, hence the -1
                drawables.Rectangle(rectX, rectY, rectX + rectWidth - 1, rectY + pixelsPerModule - 1);
            }
        }
    }
}

/// <summary>
/// Provides static methods for creating raster QR codes.
/// </summary>
public static class QRCodeHelper
{
    /// <summary>
    /// Creates a raster QR code with a single function call.
    /// </summary>
    /// <param name="plainText">The text or payload to be encoded inside the QR code.</param>
    /// <param name="pixelsPerModule">The number of pixels each dark/light module of the QR code will occupy in the final QR code image.</param>
    /// <param name="darkColor">The color of the dark modules.</param>
    /// <param name="lightColor">The color of the light modules.</param>
    /// <param name="eccLevel">The level of error correction data.</param>
    /// <param name="forceUtf8">Specifies whether the generator should be forced to work in UTF-8 mode.</param>
    /// <param name="utf8BOM">Specifies whether the byte-order-mark should be used.</param>
    /// <param name="eciMode">Specifies which ECI mode should be used.</param>
    /// <param name="requestedVersion">Sets the fixed QR code target version.</param>
    /// <param name="icon">An optional icon to be placed in the center of the QR code.</param>
    /// <param name="iconSizePercent">The size of the icon as a percentage of the QR code size.</param>
    /// <param name="iconBorderWidth">The width of the border around the icon.</param>
    /// <param name="drawQuietZones">Indicates if quiet zones around the QR code should be drawn.</param>
    /// <returns>Returns the QR code graphic as a <see cref="MagickImage"/>.</returns>
    public static MagickImage GetQRCode(string plainText, int pixelsPerModule, MagickColor darkColor, MagickColor lightColor, ECCLevel eccLevel, bool forceUtf8 = false, bool utf8BOM = false, EciMode eciMode = EciMode.Default, int requestedVersion = -1, IMagickImage<byte>? icon = null, int iconSizePercent = 15, int iconBorderWidth = 0, bool drawQuietZones = true)
    {
        using var qrGenerator = new QRCodeGenerator();
        using var qrCodeData = qrGenerator.CreateQrCode(plainText, eccLevel, forceUtf8, utf8BOM, eciMode, requestedVersion);
        using var qrCode = new QRCode(qrCodeData);
        return qrCode.GetGraphic(pixelsPerModule, darkColor, lightColor, icon, iconSizePercent, iconBorderWidth, drawQuietZones);
    }
}
