<Project Sdk="Microsoft.NET.Sdk">

  <!-- This project, when published, verifies that QRCoder is trimmable; see below link for more details. -->
  <!-- https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming -->

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QRCoder\QRCoder.csproj" />
    <TrimmerRootAssembly Include="QRCoder" />
  </ItemGroup>

</Project>
