<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows;net9.0;net9.0-windows;net10.0;net10.0-windows</TargetFrameworks>
    <UseWPF Condition="$(TargetFramework.EndsWith('-windows'))">true</UseWPF>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Commandlineparameters>--in foo --out fooQR.png</Commandlineparameters>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NDesk.Options.Core" Version="1.2.5" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.EndsWith('-windows'))">
    <ProjectReference Include="..\QRCoder.Xaml\QRCoder.Xaml.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\QRCoder\QRCoder.csproj" />
  </ItemGroup>
</Project>
